services:
  nginx:
    image: docker.io/nginx:1.26.1
    container_name: nginx_compose
    restart: always
    labels:
      - traefik.enable=true
      - providers.docker=true
      - traefik.http.routers.nginx.rule=Host(`nginx.refrain.work`)
      - traefik.http.routers.nginx.entrypoints=https
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.service=nginx
      - traefik.http.services.nginx.loadbalancer.server.port=80
    networks:
      - proxy

networks:
  proxy:
    external: true
